export const MOUNT_COMPONENT = '@@ui/MOUNT_COMPONENT';
export const UNMOUNT_COMPONENT = '@@ui/UNMOUNT_COMPONENT';
export const UPDATE_COMPONENT_STATE = '@@ui/UPDATE_COMPONENT_STATE';
export const RESET_COMPONENT_STATE = '@@ui/RESET_COMPONENT_STATE';
